site_accent_color = "#e20a39"
title_font = "Modern sans-serif"
body_font = "Elegant serif"
navigation_layout = "Logo in the middle"
site_background_color = "#ffffff"
header_and_footer_color = "Background color"
header_style = "Highlight"
show_featured_posts = true
post_feed_style = "List"
show_images_in_feed = true
show_publication_info_sidebar = "true"
cover_image = "/uploads/design/1000070462.jpg"
